### ISSUE TITLE
Cannot load ref-napi package

### ISSUE THREAD

**Issue by terenc3** [toyobayashi/asar-node#2]
When using the [ref-napi](https://www.npmjs.com/package/ref-napi) package asar-node cannot require the following file **node_modules\ref-napi\prebuilds\win32-x64\node.napi.node**. I think the if condition on [lib/register.js#L140](https://github.com/toyobayashi/asar-node/blob/master/lib/register.js#L140) is not meant for this case

**Comment by toyobayashi** [comment]
@terenc3 Can you create a pull request or provide a minimal repro?

**Comment by toyobayashi** [comment]
asar-node v3 has been released and I can't reproducing this bug with `--unpack=*.node` option. Feel free to open another issue if you experience this problem again. Close.
